os:
  - linux
  - osx
language: generic
sudo: false
dist: trusty
osx_image: xcode8.3
install:
  - eval "$(curl -sL http://sh.zewo.io/install.sh)"
script:
  - eval "$(curl -sL http://sh.zewo.io/build.sh)"