version: 2

jobs:
  macos:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: swiftdocker/swift:latest
    steps:
      - checkout
      - run: 
          name: Debug build
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test

  linux-release:
    docker:
      - image: swiftdocker/swift:latest
    steps:
      - checkout
      - run: 
          name: Release build
          command: swift build -c release

workflows:
  version: 2
  build_and_test:
    jobs:
      - linux
      - linux-release
      - macos

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                
    jobs:
      - linux
      - macos